# Generated by Django 3.0.7 on 2022-06-05 13:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menuitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('components', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, verbose_name='Продукт'), size=None)),
                ('price', models.FloatField(verbose_name='Цена')),
            ],
        ),
    ]
